name: Sync Home Assistant and HassIO Components

on:
  push:
    paths:
      - 'stable.json'

env:
  ALIYUN_REGISTRY: ${{ secrets.ALIYUN_REGISTRY }}
  ALIYUN_NAMESPACE: ${{ secrets.ALIYUN_NAMESPACE }}
  SUPPORTED_COMPONENTS: 'cli|dns|audio|multicast|observer'

jobs:
  version_monitor:
    runs-on: ubuntu-latest
    outputs:
      ha_version: ${{ steps.extract_versions.outputs.ha_version }}
      cli_version: ${{ steps.extract_versions.outputs.cli_version }}
      dns_version: ${{ steps.extract_versions.outputs.dns_version }}
      audio_version: ${{ steps.extract_versions.outputs.audio_version }}
      multicast_version: ${{ steps.extract_versions.outputs.multicast_version }}
      observer_version: ${{ steps.extract_versions.outputs.observer_version }}
      has_ha: ${{ steps.extract_versions.outputs.has_ha }}
      has_hassio: ${{ steps.extract_versions.outputs.has_hassio }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Extract versions
      id: extract_versions
      run: |
        # Get current and previous file content
        CURRENT=$(cat stable.json)
        PREVIOUS=$(git show HEAD^:stable.json 2>/dev/null || echo "{}")

        # Function to extract version from JSON
        extract_version() {
          echo "$1" | jq -r "$2" || echo ""
        }

        # Current versions
        CURRENT_HA=$(extract_version "$CURRENT" '.homeassistant.default')
        CURRENT_CLI=$(extract_version "$CURRENT" '.cli')
        CURRENT_DNS=$(extract_version "$CURRENT" '.dns')
        CURRENT_AUDIO=$(extract_version "$CURRENT" '.audio')
        CURRENT_MULTICAST=$(extract_version "$CURRENT" '.multicast')
        CURRENT_OBSERVER=$(extract_version "$CURRENT" '.observer')

        # Previous versions
        PREVIOUS_HA=$(extract_version "$PREVIOUS" '.homeassistant.default')
        PREVIOUS_CLI=$(extract_version "$PREVIOUS" '.cli')
        PREVIOUS_DNS=$(extract_version "$PREVIOUS" '.dns')
        PREVIOUS_AUDIO=$(extract_version "$PREVIOUS" '.audio')
        PREVIOUS_MULTICAST=$(extract_version "$PREVIOUS" '.multicast')
        PREVIOUS_OBSERVER=$(extract_version "$PREVIOUS" '.observer')

        # Set outputs for changed versions
        if [ "$CURRENT_HA" != "$PREVIOUS_HA" ] && [ -n "$CURRENT_HA" ]; then
          echo "ha_version=$CURRENT_HA" >> $GITHUB_OUTPUT
          echo "has_ha=true" >> $GITHUB_OUTPUT
        else
          echo "has_ha=false" >> $GITHUB_OUTPUT
        fi

        HAS_HASSIO=false
        if [ "$CURRENT_CLI" != "$PREVIOUS_CLI" ] && [ -n "$CURRENT_CLI" ]; then
          echo "cli_version=$CURRENT_CLI" >> $GITHUB_OUTPUT
          HAS_HASSIO=true
        fi

        if [ "$CURRENT_DNS" != "$PREVIOUS_DNS" ] && [ -n "$CURRENT_DNS" ]; then
          echo "dns_version=$CURRENT_DNS" >> $GITHUB_OUTPUT
          HAS_HASSIO=true
        fi

        if [ "$CURRENT_AUDIO" != "$PREVIOUS_AUDIO" ] && [ -n "$CURRENT_AUDIO" ]; then
          echo "audio_version=$CURRENT_AUDIO" >> $GITHUB_OUTPUT
          HAS_HASSIO=true
        fi

        if [ "$CURRENT_MULTICAST" != "$PREVIOUS_MULTICAST" ] && [ -n "$CURRENT_MULTICAST" ]; then
          echo "multicast_version=$CURRENT_MULTICAST" >> $GITHUB_OUTPUT
          HAS_HASSIO=true
        fi

        if [ "$CURRENT_OBSERVER" != "$PREVIOUS_OBSERVER" ] && [ -n "$CURRENT_OBSERVER" ]; then
          echo "observer_version=$CURRENT_OBSERVER" >> $GITHUB_OUTPUT
          HAS_HASSIO=true
        fi

        echo "has_hassio=$HAS_HASSIO" >> $GITHUB_OUTPUT

    - name: Output version changes
      run: |
        echo "=== 检测到的版本变化 ==="
        if [ "${{ steps.extract_versions.outputs.has_ha }}" = "true" ]; then
          echo "homeassistant: ${{ steps.extract_versions.outputs.ha_version }}"
        fi
        [ -n "${{ steps.extract_versions.outputs.cli_version }}" ] && echo "cli: ${{ steps.extract_versions.outputs.cli_version }}"
        [ -n "${{ steps.extract_versions.outputs.dns_version }}" ] && echo "dns: ${{ steps.extract_versions.outputs.dns_version }}"
        [ -n "${{ steps.extract_versions.outputs.audio_version }}" ] && echo "audio: ${{ steps.extract_versions.outputs.audio_version }}"
        [ -n "${{ steps.extract_versions.outputs.multicast_version }}" ] && echo "multicast: ${{ steps.extract_versions.outputs.multicast_version }}"
        [ -n "${{ steps.extract_versions.outputs.observer_version }}" ] && echo "observer: ${{ steps.extract_versions.outputs.observer_version }}"

  # Home Assistant 同步任务
  sync_homeassistant:
    needs: version_monitor
    if: ${{ needs.version_monitor.outputs.has_ha == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - 'home-assistant'
          - 'amd64-homeassistant'
          - 'i386-homeassistant'
          - 'armhf-homeassistant'
          - 'armv7-homeassistant'
          - 'aarch64-homeassistant'
          - 'generic-x86-64-homeassistant'
          - 'intel-nuc-homeassistant'
          - 'khadas-vim3-homeassistant'
          - 'odroid-c2-homeassistant'
          - 'odroid-c4-homeassistant'
          - 'odroid-m1-homeassistant'
          - 'odroid-n2-homeassistant'
          - 'odroid-xu-homeassistant'
          - 'qemuarm-homeassistant'
          - 'qemuarm-64-homeassistant'
          - 'qemux86-homeassistant'
          - 'qemux86-64-homeassistant'
          - 'raspberrypi-homeassistant'
          - 'raspberrypi2-homeassistant'
          - 'raspberrypi3-homeassistant'
          - 'raspberrypi3-64-homeassistant'
          - 'raspberrypi4-homeassistant'
          - 'raspberrypi4-64-homeassistant'
          - 'raspberrypi5-64-homeassistant'
          - 'tinker-homeassistant'
          - 'yellow-homeassistant'
          - 'green-homeassistant'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker
        run: |
          sudo systemctl start docker
          docker --version
          docker info

      - name: Login to Aliyun
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Process Home Assistant image
        run: |
          version="${{ needs.version_monitor.outputs.ha_version }}"
          SRC_IMAGE="ghcr.io/home-assistant/${{ matrix.arch }}"
          DEST_IMAGE="${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAMESPACE }}/${{ matrix.arch }}"

          echo "正在同步 ${{ matrix.arch }} 版本 $version"
          
          docker pull "${SRC_IMAGE}:${version}" || {
            echo "::warning::跳过 ${{ matrix.arch }}:${version}"
            exit 0
          }

          # 打标签
          docker tag "${SRC_IMAGE}:${version}" "${DEST_IMAGE}:${version}"
          docker tag "${SRC_IMAGE}:${version}" "${DEST_IMAGE}:latest"

          # 主镜像特殊标签
          if [ "${{ matrix.arch }}" = "home-assistant" ]; then
            ym_tag=$(echo "${version}" | awk -F. '{print $1"."$2}')
            docker tag "${SRC_IMAGE}:${version}" "${DEST_IMAGE}:stable"
            docker tag "${SRC_IMAGE}:${version}" "${DEST_IMAGE}:${ym_tag}"
          fi

          # 推送
          echo "推送镜像到阿里云..."
          docker push "${DEST_IMAGE}:${version}"
          docker push "${DEST_IMAGE}:latest"
          [ "${{ matrix.arch }}" = "home-assistant" ] && docker push "${DEST_IMAGE}:stable"
          [ "${{ matrix.arch }}" = "home-assistant" ] && docker push "${DEST_IMAGE}:${ym_tag}"

          # 清理
          echo "清理镜像..."
          docker rmi "${SRC_IMAGE}:${version}" || true
          [ "${{ matrix.arch }}" = "home-assistant" ] && docker rmi "${DEST_IMAGE}:${ym_tag}" || true

  # HassIO 组件同步任务
  sync_hassio:
    needs: version_monitor
    if: ${{ needs.version_monitor.outputs.has_hassio == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker
        run: |
          sudo systemctl start docker
          docker --version
          docker info

      - name: Login to Aliyun
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Sync HassIO Components
        run: |
          # 定义同步函数
          sync_component() {
            local component=$1
            local version=$2
            local archs=("amd64" "i386" "armhf" "armv7" "aarch64")
            
            echo "=== 开始同步 $component 版本 $version ==="
            
            for arch in "${archs[@]}"; do
              SRC_IMAGE="ghcr.io/home-assistant/${arch}-hassio-${component}"
              DEST_IMAGE="${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAMESPACE }}/${arch}-hassio-${component}"

              echo "处理架构 $arch..."
              
              docker pull "${SRC_IMAGE}:${version}" || {
                echo "::warning::镜像不存在 ${SRC_IMAGE}:${version}，跳过此架构"
                continue
              }

              echo "打标签..."
              docker tag "${SRC_IMAGE}:${version}" "${DEST_IMAGE}:${version}"
              docker tag "${SRC_IMAGE}:${version}" "${DEST_IMAGE}:latest"

              echo "推送镜像..."
              docker push "${DEST_IMAGE}:${version}"
              docker push "${DEST_IMAGE}:latest"

              echo "清理镜像..."
              docker rmi "${SRC_IMAGE}:${version}" || true
              docker rmi "${DEST_IMAGE}:${version}" || true
              docker rmi "${DEST_IMAGE}:latest" || true
            done
          }

          # 同步各组件
          [ -n "${{ needs.version_monitor.outputs.cli_version }}" ] && sync_component "cli" "${{ needs.version_monitor.outputs.cli_version }}"
          [ -n "${{ needs.version_monitor.outputs.dns_version }}" ] && sync_component "dns" "${{ needs.version_monitor.outputs.dns_version }}"
          [ -n "${{ needs.version_monitor.outputs.audio_version }}" ] && sync_component "audio" "${{ needs.version_monitor.outputs.audio_version }}"
          [ -n "${{ needs.version_monitor.outputs.multicast_version }}" ] && sync_component "multicast" "${{ needs.version_monitor.outputs.multicast_version }}"
          [ -n "${{ needs.version_monitor.outputs.observer_version }}" ] && sync_component "observer" "${{ needs.version_monitor.outputs.observer_version }}"